### ISSUE TITLE
guys don't waste your time on this "node" it not workging anymore.

### ISSUE THREAD

**Issue by EKKIVOK01** [TemryL/ComfyUI-IDM-VTON#89]
and you will not have a response from the author. 
It's been 3 days (full) to get this node working i changed version of all my setup roll back etc...and it's impossible you will get ALL THE TIME import failed. people complaining about that are simply ignored.

Don't waste your time on that thing.

**Comment by emmgr23** [comment]
It's been a week for me 😂 Have you found another alternative?

**Comment by EKKIVOK01** [comment]
> It's been a week for me 😂 Have you found another alternative?

yep throw this to trash, but you can still use an earlier version of torch and pytorch and should be working...

**Comment by Andypwk** [comment]
damn it wasn't only my problem. Usually, I don't try to find develop issus when I got trouble with kinda software conflict problem coz I like solve it with my new code but this trash makes me to come to here.

**Comment by shynsky** [comment]
@EKKIVOK01 Which versions work for you?

**Comment by tjengbudi** [comment]
installed new comfyui, and then installed idm-vton and it installed with no error.
running comfyui found some depracated but running. 
still not download model by myself yet. will be inform more later

**Comment by tjengbudi** [comment]
i can install it with no error, just warning about deprecated because of a different version
the main problem I faced was my gpu, I just used a RTX3060 12gb vram. when i try it it is 6 hours and still running. 
I read some posts in the internet; someone already can tweak it to run smoothly. but not found what i have done before idm-vton running
but installing is ok. no error

**Comment by vvvk-gh** [comment]
Hi Guys,
I need to build same kind of workflow can some one guide me how can i one setup and run such workflows locally and what is the best envinorment or laptop requirements to run these.

**Comment by TemryL** [comment]
Hey guys, sorry for the late reply, I put this project aside for a while. The main issue is dependencies conflict with `diffusers` from `HuggingFace`.  Ideally, we should drop diffusers from this project and solely use implementation from `ComfyUI`, I will work on that from now, but I can't promise anything as the original code of `idm-vton` is based on HF implementation and is pretty hacky to be honest.

**Comment by nikhil-tayal** [comment]
This is still not working. Also tried CatVton but facing issues in that wrapper also. Do we have some other wrapper for VTON which is working fine?

**Comment by bobcate** [comment]
This works if you:
- Apply [this fix](https://github.com/TemryL/ComfyUI-IDM-VTON/issues/92) (it's safe)
- Downgrade the package `peft` to `0.13.2` (they say the latest version has a bug)

Also, I had `diffusers 0.27.2`, for some reason, which was giving me a different error. I upgraded it to `0.30.3` and it's working now.
